# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build pdoc3

      - name: Regenerate documentation
        run: |
          pdoc3 --html edupage_api
          rm -rf docs
          mv html/edupage_api docs

      - name: Commit and push documentation changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          default_author: github_actions
          message: "Regenerate documentation"

          pathspec_error_handling: ignore
          push: origin master

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          twine upload dist/*
